### ISSUE TITLE
Add option to upload data files

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/chance-water-distribution#27]
This should include a custom network with coordinates and pollution data

Make sure to also add instructions regarding the specific file types and structures, including the metadata file. We should probably think that the key person to use this feature will be the RA that replaces Alessio.

**Comment by edwardchalstrey1** [comment]
Create a different branch that has this feature, because we only want it to run in the local version

**Comment by edwardchalstrey1** [comment]
Unfortunately, doesn't look like there's an easy way to do this with Bokeh: https://stackoverflow.com/questions/40794180/upload-a-csv-file-and-read-it-in-bokeh-web-app

**Comment by edwardchalstrey1** [comment]
@JimMadge Would it be possible to add the Docker file that you're using to run the bokeh server on azure to the repo? My thinking is that rather than attempting to implement an "Upload files" button, it would be easier to have people that want to load a custom network to do so with Docker, with the files as command line args when running the container (or something along these lines). Running `docker run water_app file1 file2` etc should be easier than cloning the repo then running `bokeh serve` in any case.

**Comment by edwardchalstrey1** [comment]
Ah, I see you added a separate issue #101

**Comment by JimMadge** [comment]
@edwardchalstrey1 Yep, I haven't make a Dockerfile yet, but it should be quite straightfoward if we start from the Python container. Install requirements from requirements.txt, copy across the water directory, then run bokeh serve.

**Comment by edwardchalstrey1** [comment]
Might be possible to use Flask to add an upload widget, see Jim suggestion in #105
