### ISSUE TITLE
Investigate warning message

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/chance-water-distribution#73]
I can't see what impact this has on functionality, but thought I'd raise an issue anyway in case it has effects later on. Get this in the terminal when starting the app:
 `BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('pollution_value', 0), ('time', 1331)`

**Comment by JimMadge** [comment]
@edwardchalstrey1 Doesn't seem to cause a problem, but it is probably worth sorting out.

I think it will be to do with the pollution history at `initialisation,`
```
pollution_history_source.data['time'] = history.index
pollution_history_source.data['pollution_value'] = history.values
```
