### ISSUE TITLE
Host the bokeh app on a public website

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/chance-water-distribution#90]
Would be cool if we could get the app to update on every update to master branch, perhaps using GH pages: https://p-mckenzie.github.io/2017/12/01/embedding-bokeh-with-github-pages/

**Comment by edwardchalstrey1** [comment]
Run server on azure vm and get a url to point to it

**Comment by JimMadge** [comment]
Closed in #100
